# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('addons', 'addons'),
    ],
    hiddenimports=[
        'core', 'core.loader', 'core.workers', 'core.workers.database_worker',
        'core.workers.query_cache', 'core.base_module', 'core.alerts',
        'core.logger', 'core.database', 'core.widgets.global_loader',
        'core.local_db', 'module_detector', 'certificate_manager',
        'addons.Paramètres.views.setup_view',
        'addons.Paramètres.controllers.setup_controller',
        'addons.Paramètres.views.loggin_view',
        'addons.Paramètres.controllers.login_controller',
        'addons.Paramètres.models.models',
        'numpy', 'numpy.core', 'numpy.core._multiarray_umath',
        'numpy.random', 'numpy.linalg', 'numpy.fft',
        'pandas', 'pandas.core', 'pandas.io', 'pandas.io.sql',
        'pandas.io.parsers', 'pandas.io.excel', 'pandas.io.json',
        'sqlalchemy', 'sqlalchemy.dialects.postgresql',
        'sqlalchemy.ext.declarative', 'sqlalchemy.orm',
        'psycopg2', 'psycopg2._psycopg', 'psycopg2.extensions',
        'psycopg2.extras', 'psycopg2.pool', 'psycopg2.sql',
        'psycopg2.errorcodes', 'PySide6', 'PySide6.QtCore',
        'PySide6.QtWidgets', 'PySide6.QtGui', 'PySide6.QtNetwork',
        'PySide6.QtSvg', 'PySide6.QtPrintSupport', 'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets', 'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets', 'PySide6.QtSql', 'PySide6.QtXml',
        'PySide6.QtCharts', 'qrcode', 'qrcode.image.pil',
        'PIL', 'PIL.Image', 'PIL.ImageDraw', 'PIL.ImageFont',
        'PIL.ImageFilter', 'PIL.ImageEnhance', 'PIL.ImageColor',
        'reportlab', 'reportlab.lib', 'reportlab.lib.pagesizes',
        'reportlab.lib.units', 'reportlab.lib.colors',
        'reportlab.pdfbase', 'reportlab.pdfgen',
        'reportlab.platypus', 'openpyxl', 'openpyxl.cell',
        'openpyxl.reader', 'openpyxl.workbook', 'openpyxl.writer',
        'openpyxl.styles', 'openpyxl.formatting', 'openpyxl.chart',
        'openpyxl.utils', 'bcrypt', 'flask', 'flask.views',
        'flask.json', 'flask_cors', 'requests',
        'requests.packages', 'requests.packages.urllib3',
        'urllib3', 'certifi', 'idna', 'charset_normalizer',
        'python_dateutil', 'dateutil.parser', 'dateutil.tz',
        'dateutil.relativedelta', 'dotenv', 'greenlet',
        'packaging', 'packaging.version', 'packaging.specifiers',
        'typing_extensions', 'six', 'et_xmlfile', 'xlrd',
        'altgraph', 'colorama', 'setuptools', 'shiboken6',
        'cffi', 'cryptography', 'jinja2', 'markupsafe',
        'itsdangerous', 'click', 'werkzeug', 'pytz', 'tzdata',
        'pyqtgraph', 'pyqtgraph.Qt', 'pyqtgraph.graphicsItems',
        'pyqtgraph.widgets', 'email', 'email.mime', 'email.mime.multipart',
        'email.mime.text', 'email.mime.base', 'email.mime.image',
        'email.mime.application', 'email.encoders', 'email.utils',
        'smtplib'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LOMETA',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
)
