# addons/Automobiles/utils/cities.py

CITIES_BY_COUNTRY = {
    "CAMEROUN": [
        "DOUALA", "YAOUNDE", "GAROUA", "BAMENDA", "MAROUA",
        "BAFOUSSAM", "NGAOUNDERE", "BERTHOUA", "KOUSSERI", "LOUM",
        "EDEA", "KUMBA", "MEIGANGA", "FOUMPBAN", "TIKO",
        "BUEA", "LIMBE", "BATOURI", "YABASSI", "MOULVOUDAYE",
        "NGAOUNDAL", "GUIDER", "BEKOKO", "KAELE", "LAGDO",
        "AKONOLINGA", "BANGANGTE", "BANKIM", "BATCHAM", "BATIBO",
        "BEFANG", "BENOIT", "BOGO", "BUEA", "DIZANGUE"
    ],
    "FRANCE": [
        "PARIS", "LYON", "MARSEILLE", "TOULOUSE", "NICE",
        "NANTES", "STRASBOURG", "MONTPELLIER", "BORDEAUX", "LILLE",
        "RENNES", "REIMS", "SAINT-ETIENNE", "TOULON", "GRENOBLE",
        "ANGERS", "DIJON", "BREST", "LE MANS", "CLERMONT-FERRAND",
        "AMIENS", "AIX-EN-PROVENCE", "LIMOGES", "NIMES", "TOURS",
        "METZ", "BESANCON", "PERPIGNAN", "ORLEANS", "ROUEN"
    ],
    "ALGERIE": [
        "ALGER", "ORAN", "CONSTANTINE", "ANNABA", "BLIDA",
        "BATNA", "DJELFA", "SETIF", "SIDI BEL ABBES", "BISKRA",
        "TEBESSA", "TIPASA", "TIZI-OUZOU", "BOUIRA", "BEJAIA"
    ],
    "COTE D'IVOIRE": [
        "ABIDJAN", "BOUAKE", "YAMOUSSOUKRO", "DALOA", "KORHOGO",
        "SAN PEDRO", "MAN", "DUEKOUE", "ABENGOUROU", "AGBOVILLE"
    ],
    "SENEGAL": [
        "DAKAR", "THIES", "SAINT-LOUIS", "KAOLACK", "ZIGUINCHOR",
        "TAMBACOUNDA", "MBOUR", "LOUGA", "KEDOUGOU", "SEDHIOU"
    ],
    "GABON": [
        "LIBREVILLE", "PORT-GENTIL", "FRANCEVILLE", "OYEM", "LAMBARENE",
        "MOANDA", "TCHIBANGA", "MOUILA", "GAMBA", "BITAM"
    ],
    "CONGO": [
        "BRAZZAVILLE", "POINTE-NOIRE", "DOLISIE", "MAKOUA", "OUESSO",
        "NTOU", "LOUBOMO", "SOUE", "MADINGOU", "PANGALA"
    ],
    "CONGO (RDC)": [
        "KINSHASA", "LUBUMBASHI", "MBUJI-MAYI", "KISANGANI", "KANANGA",
        "GOMA", "BUKAVU", "KOLWEZI", "KINDU", "UVIRA"
    ],
    "BURKINA FASO": [
        "OUAGADOUGOU", "BOBO-DIOULASSO", "KOUDOUGOU", "BANFORA", "DEDOUGOU",
        "KAYA", "FADA N'GOURMA", "TENKODOGO", "PO", "OUAHIGOUYA"
    ],
    "NIGER": [
        "NIAMEY", "ZINDER", "MARADI", "AGADEZ", "TAHOUA",
        "DOSSO", "TILLABERI", "GAYA", "BIRNI N'KONNI", "DIFFA"
    ],
    "MALI": [
        "BAMAKO", "SIKASSO", "KAYES", "MOPTI", "GAO",
        "SEGOU", "KOUTIALA", "TOMBOUCTOU", "BOUGOUNI", "KITA"
    ],
    "BENIN": [
        "COTONOU", "PORTO-NOVO", "PARAKOU", "ABOMEY", "DJOUGOU",
        "NATITINGOU", "KANDI", "OUIDAH", "ADJARRA", "SAKETE"
    ],
    "TOGO": [
        "LOME", "SOKODE", "KARA", "ATAKPAME", "PALIME",
        "BASSAR", "DAKPAM", "TCHAMBA", "KPELE", "TAVE"
    ],
    "CENTRAFRIQUE": [
        "BANGUI", "BIMBO", "BERBERATI", "BANGASSOU", "BAMBARI",
        "BOUAR", "BOZUM", "BRIA", "BOSSANGOA", "KAGA-BANDORO"
    ],
    "TCHAD": [
        "N'DJAMENA", "MOUDOU", "SARH", "ABECHE", "DABOUA",
        "PALA", "AM TIMAN", "BONGOR", "GOUNDI", "KOUMA"
    ],
    "MAURITANIE": [
        "NOUAKCHOTT", "NOUADHIBOU", "KIFFA", "ATAR", "ZOUERATE",
        "AIOUN", "AKJOUJT", "BOGUE", "NEMA", "SELIBABY"
    ],
    "MAROC": [
        "CASABLANCA", "RABAT", "FES", "MARRAKECH", "AGADIR",
        "TANGER", "MOHAMMEDIA", "KENITRA", "OUJDA", "MEKNES",
        "SAFI", "TETOUAN", "EL JADIDA", "LAYOUNE", "BENI MELLAL"
    ],
    "TUNISIE": [
        "TUNIS", "SOUSSE", "SFARS", "BEN AROUS", "GABES",
        "NABEUL", "KAIROUAN", "MONASTIR", "BISERTE", "JENDOUBA"
    ],
    "EGYPTE": [
        "LE CAIRE", "ALEXANDRIE", "GIZEH", "PORT-SAID", "SOUSSE",
        "LUXOR", "ASSOUAN", "ISMAILIA", "MANSOURA", "TANTA"
    ],
    "SUISSE": [
        "ZURICH", "GENEVE", "BALE", "LAUSANNE", "BERNE",
        "LUCERNE", "ST-GALL", "WINTERTHOUR", "FRIBOURG", "BIEL",
        "NEUCHATEL", "SION", "SCHWYTZ", "ALTDORF", "APPENZELL"
    ],
    "BELGIQUE": [
        "BRUXELLES", "ANVERS", "GAND", "CHARLEROI", "LIEGE",
        "BRUGES", "NAMUR", "MONS", "LOUVAIN", "COURTRAI"
    ],
    "CANADA": [
        "OTTAWA", "TORONTO", "MONTREAL", "VANCOUVER", "CALGARY",
        "EDMONTON", "QUEBEC", "WINNIPEG", "HALIFAX", "LONDON"
    ],
    "ETATS-UNIS": [
        "WASHINGTON", "NEW YORK", "LOS ANGELES", "CHICAGO", "HOUSTON",
        "PHOENIX", "PHILADELPHIE", "SAN ANTONIO", "SAN DIEGO", "DALLAS"
    ],
    "ROYAUME-UNI": [
        "LONDRES", "MANCHESTER", "BIRMINGHAM", "LEEDS", "GLASGOW",
        "LIVERPOOL", "NEWCASTLE", "BRISTOL", "SHEFFIELD", "EDIMBOURG"
    ],
    "ALLEMAGNE": [
        "BERLIN", "MUNICH", "FRANCFORT", "COLOGNE", "STUTTGART",
        "DUSSELDORF", "DRESDE", "LEIPZIG", "NUREMBERG", "HANNOVER"
    ],
    "ITALIE": [
        "ROME", "MILAN", "NAPLES", "TURIN", "PALERME",
        "GENES", "BOLOGNE", "FLORENCE", "VENISE", "VERONE"
    ],
    "ESPAGNE": [
        "MADRID", "BARCELONE", "VALENCE", "SEVILLE", "BILBAO",
        "SARAGOSSE", "MALAGA", "LAS PALMAS", "PALMA", "GRENADE"
    ],
    "PORTUGAL": [
        "LISBONNE", "PORTO", "BRAGA", "COIMBRE", "AVEIRO",
        "FARO", "SETUBAL", "VISEU", "LEIRIA", "ALBUFEIRA"
    ],
    "PAYS-BAS": [
        "AMSTERDAM", "ROTTERDAM", "LA HAYE", "UTRECHT", "EINDHOVEN",
        "GRONINGUE", "BREDA", "NIMEGUE", "APELDOORN", "HARLEM"
    ],
    "CHINE": [
        "PEKIN", "SHANGHAI", "HONG KONG", "CANTON", "TIANJIN",
        "WUHAN", "NANJING", "CHENGDU", "SHENYANG", "CHONGQING"
    ],
    "JAPON": [
        "TOKYO", "OSAKA", "YOKOHAMA", "NAGOYA", "SAPPORO",
        "FUKUOKA", "KOBE", "KYOTO", "HIROSHIMA", "SENDAI"
    ],
    "RUSSIE": [
        "MOSCOU", "SAINT-PETERSBOURG", "NOVOSSIBIRSK", "EKATERINBOURG", "KAZAN",
        "NIZHNI NOVGOROD", "TCHELIABINSK", "ROSTOV", "OFA", "VOLGOGRAD"
    ],
    "INDE": [
        "NEW DELHI", "MUMBAI", "BANGALORE", "CHENNAI", "KOLKATA",
        "HYDERABAD", "PUNE", "AHMEDABAD", "JAIPUR", "LUCKNOW"
    ],
    "BRESIL": [
        "BRASILIA", "SAO PAULO", "RIO DE JANEIRO", "SALVADOR", "FORTALEZA",
        "BELO HORIZONTE", "MANAUS", "CURITIBA", "RECIFE", "PORTO ALEGRE"
    ],
    "MEXIQUE": [
        "MEXICO", "GUADALAJARA", "MONTERREY", "PUEBLA", "TOLUCA",
        "TIJUANA", "LEON", "QUERETARO", "MERIDA", "CHIHUAHUA"
    ],
    "AUSTRALIE": [
        "CANBERRA", "SYDNEY", "MELBOURNE", "BRISBANE", "PERTH",
        "ADELAIDE", "GOLD COAST", "NEWCASTLE", "WOLLONGONG", "HOBART"
    ],
    "AFRIQUE DU SUD": [
        "PRETORIA", "LE CAP", "JOHANNESBURG", "DURBAN", "PORT ELIZABETH",
        "BLOEMFONTEIN", "PIETERMARITZBURG", "NELSPRUIT", "KIMBERLEY", "EAST LONDON"
    ]
}

# Liste des pays disponibles
COUNTRIES_WITH_CITIES = list(CITIES_BY_COUNTRY.keys())