# addons/Automobiles/utils/countries.py

COUNTRIES_WITH_CODES = [
    {"code": "CM", "name": "CAMEROUN"},
    {"code": "AF", "name": "AFGHANISTAN"},
    {"code": "ZA", "name": "AFRIQUE DU SUD"},
    {"code": "AL", "name": "ALBANIE"},
    {"code": "DZ", "name": "ALGERIE"},
    {"code": "DE", "name": "ALLEMAGNE"},
    {"code": "AD", "name": "ANDORRE"},
    {"code": "AO", "name": "ANGOLA"},
    {"code": "AG", "name": "ANTIGUA-ET-BARBUDA"},
    {"code": "SA", "name": "ARABIE SAOUDITE"},
    {"code": "AR", "name": "ARGENTINE"},
    {"code": "AM", "name": "ARMENIE"},
    {"code": "AU", "name": "AUSTRALIE"},
    {"code": "AT", "name": "AUTRICHE"},
    {"code": "AZ", "name": "AZERBAIDJAN"},
    {"code": "BS", "name": "BAHAMAS"},
    {"code": "BH", "name": "BAHREIN"},
    {"code": "BD", "name": "BANGLADESH"},
    {"code": "BB", "name": "BARBADE"},
    {"code": "BY", "name": "BELARUS"},
    {"code": "BE", "name": "BELGIQUE"},
    {"code": "BZ", "name": "BELIZE"},
    {"code": "BJ", "name": "BENIN"},
    {"code": "BT", "name": "BHOUTAN"},
    {"code": "MM", "name": "BIRMANIE"},
    {"code": "BO", "name": "BOLIVIE"},
    {"code": "BA", "name": "BOSNIE-HERZEGOVINE"},
    {"code": "BW", "name": "BOTSWANA"},
    {"code": "BR", "name": "BRESIL"},
    {"code": "BN", "name": "BRUNEI"},
    {"code": "BG", "name": "BULGARIE"},
    {"code": "BF", "name": "BURKINA FASO"},
    {"code": "BI", "name": "BURUNDI"},
    {"code": "KH", "name": "CAMBODGE"},
    {"code": "CA", "name": "CANADA"},
    {"code": "CV", "name": "CAP-VERT"},
    {"code": "CF", "name": "CENTRAFRIQUE"},
    {"code": "CL", "name": "CHILI"},
    {"code": "CN", "name": "CHINE"},
    {"code": "CY", "name": "CHYPRE"},
    {"code": "CO", "name": "COLOMBIE"},
    {"code": "KM", "name": "COMORES"},
    {"code": "CG", "name": "CONGO"},
    {"code": "CD", "name": "CONGO (RDC)"},
    {"code": "KP", "name": "COREE DU NORD"},
    {"code": "KR", "name": "COREE DU SUD"},
    {"code": "CR", "name": "COSTA RICA"},
    {"code": "CI", "name": "COTE D'IVOIRE"},
    {"code": "HR", "name": "CROATIE"},
    {"code": "CU", "name": "CUBA"},
    {"code": "DK", "name": "DANEMARK"},
    {"code": "DJ", "name": "DJIBOUTI"},
    {"code": "DM", "name": "DOMINIQUE"},
    {"code": "EG", "name": "EGYPTE"},
    {"code": "SV", "name": "EL SALVADOR"},
    {"code": "AE", "name": "EMIRATS ARABES UNIS"},
    {"code": "EC", "name": "EQUATEUR"},
    {"code": "ER", "name": "ERYTHREE"},
    {"code": "ES", "name": "ESPAGNE"},
    {"code": "EE", "name": "ESTONIE"},
    {"code": "SZ", "name": "ESWATINI"},
    {"code": "US", "name": "ETATS-UNIS"},
    {"code": "ET", "name": "ETHIOPIE"},
    {"code": "FJ", "name": "FIDJI"},
    {"code": "FI", "name": "FINLANDE"},
    {"code": "FR", "name": "FRANCE"},
    {"code": "GA", "name": "GABON"},
    {"code": "GM", "name": "GAMBIE"},
    {"code": "GE", "name": "GEORGIE"},
    {"code": "GH", "name": "GHANA"},
    {"code": "GR", "name": "GRECE"},
    {"code": "GD", "name": "GRENADE"},
    {"code": "GT", "name": "GUATEMALA"},
    {"code": "GN", "name": "GUINEE"},
    {"code": "GW", "name": "GUINEE-BISSAU"},
    {"code": "GQ", "name": "GUINEE EQUATORIALE"},
    {"code": "GY", "name": "GUYANA"},
    {"code": "HT", "name": "HAITI"},
    {"code": "HN", "name": "HONDURAS"},
    {"code": "HU", "name": "HONGRIE"},
    {"code": "IN", "name": "INDE"},
    {"code": "ID", "name": "INDONESIE"},
    {"code": "IQ", "name": "IRAK"},
    {"code": "IR", "name": "IRAN"},
    {"code": "IE", "name": "IRLANDE"},
    {"code": "IS", "name": "ISLANDE"},
    {"code": "IL", "name": "ISRAEL"},
    {"code": "IT", "name": "ITALIE"},
    {"code": "JM", "name": "JAMAIQUE"},
    {"code": "JP", "name": "JAPON"},
    {"code": "JO", "name": "JORDANIE"},
    {"code": "KZ", "name": "KAZAKHSTAN"},
    {"code": "KE", "name": "KENYA"},
    {"code": "KG", "name": "KIRGHIZISTAN"},
    {"code": "KI", "name": "KIRIBATI"},
    {"code": "XK", "name": "KOSOVO"},
    {"code": "KW", "name": "KOWEIT"},
    {"code": "LA", "name": "LAOS"},
    {"code": "LS", "name": "LESOTHO"},
    {"code": "LV", "name": "LETTONIE"},
    {"code": "LB", "name": "LIBAN"},
    {"code": "LR", "name": "LIBERIA"},
    {"code": "LY", "name": "LIBYE"},
    {"code": "LI", "name": "LIECHTENSTEIN"},
    {"code": "LT", "name": "LITUANIE"},
    {"code": "LU", "name": "LUXEMBOURG"},
    {"code": "MK", "name": "MACEDOINE"},
    {"code": "MG", "name": "MADAGASCAR"},
    {"code": "MY", "name": "MALAISIE"},
    {"code": "MW", "name": "MALAWI"},
    {"code": "MV", "name": "MALDIVES"},
    {"code": "ML", "name": "MALI"},
    {"code": "MT", "name": "MALTE"},
    {"code": "MA", "name": "MAROC"},
    {"code": "MH", "name": "MARSHALL"},
    {"code": "MU", "name": "MAURICE"},
    {"code": "MR", "name": "MAURITANIE"},
    {"code": "MX", "name": "MEXIQUE"},
    {"code": "FM", "name": "MICRONESIE"},
    {"code": "MD", "name": "MOLDAVIE"},
    {"code": "MC", "name": "MONACO"},
    {"code": "MN", "name": "MONGOLIE"},
    {"code": "ME", "name": "MONTENEGRO"},
    {"code": "MZ", "name": "MOZAMBIQUE"},
    {"code": "NA", "name": "NAMIBIE"},
    {"code": "NR", "name": "NAURU"},
    {"code": "NP", "name": "NEPAL"},
    {"code": "NI", "name": "NICARAGUA"},
    {"code": "NE", "name": "NIGER"},
    {"code": "NG", "name": "NIGERIA"},
    {"code": "NO", "name": "NORVEGE"},
    {"code": "NZ", "name": "NOUVELLE-ZELANDE"},
    {"code": "OM", "name": "OMAN"},
    {"code": "UG", "name": "OUGANDA"},
    {"code": "UZ", "name": "OUZBEKISTAN"},
    {"code": "PK", "name": "PAKISTAN"},
    {"code": "PW", "name": "PALAU"},
    {"code": "PA", "name": "PANAMA"},
    {"code": "PG", "name": "PAPOUASIE-NOUVELLE-GUINEE"},
    {"code": "PY", "name": "PARAGUAY"},
    {"code": "NL", "name": "PAYS-BAS"},
    {"code": "PE", "name": "PEROU"},
    {"code": "PH", "name": "PHILIPPINES"},
    {"code": "PL", "name": "POLOGNE"},
    {"code": "PT", "name": "PORTUGAL"},
    {"code": "QA", "name": "QATAR"},
    {"code": "DO", "name": "REPUBLIQUE DOMINICAINE"},
    {"code": "CZ", "name": "REPUBLIQUE TCHEQUE"},
    {"code": "RO", "name": "ROUMANIE"},
    {"code": "GB", "name": "ROYAUME-UNI"},
    {"code": "RU", "name": "RUSSIE"},
    {"code": "RW", "name": "RWANDA"},
    {"code": "KN", "name": "SAINT-CHRISTOPHE-ET-NIEVES"},
    {"code": "SM", "name": "SAINT-MARIN"},
    {"code": "VC", "name": "SAINT-VINCENT-ET-LES-GRENADINES"},
    {"code": "LC", "name": "SAINTE-LUCIE"},
    {"code": "WS", "name": "SAMOA"},
    {"code": "ST", "name": "SAO TOME-ET-PRINCIPE"},
    {"code": "SN", "name": "SENEGAL"},
    {"code": "RS", "name": "SERBIE"},
    {"code": "SC", "name": "SEYCHELLES"},
    {"code": "SL", "name": "SIERRA LEONE"},
    {"code": "SG", "name": "SINGAPOUR"},
    {"code": "SK", "name": "SLOVAQUIE"},
    {"code": "SI", "name": "SLOVENIE"},
    {"code": "SO", "name": "SOMALIE"},
    {"code": "SD", "name": "SOUDAN"},
    {"code": "SS", "name": "SOUDAN DU SUD"},
    {"code": "LK", "name": "SRI LANKA"},
    {"code": "SE", "name": "SUEDE"},
    {"code": "CH", "name": "SUISSE"},
    {"code": "SR", "name": "SURINAM"},
    {"code": "SY", "name": "SYRIE"},
    {"code": "TJ", "name": "TADJIKISTAN"},
    {"code": "TW", "name": "TAIWAN"},
    {"code": "TZ", "name": "TANZANIE"},
    {"code": "TD", "name": "TCHAD"},
    {"code": "TH", "name": "THAILANDE"},
    {"code": "TL", "name": "TIMOR ORIENTAL"},
    {"code": "TG", "name": "TOGO"},
    {"code": "TO", "name": "TONGA"},
    {"code": "TT", "name": "TRINITE-ET-TOBAGO"},
    {"code": "TN", "name": "TUNISIE"},
    {"code": "TM", "name": "TURKMENISTAN"},
    {"code": "TR", "name": "TURQUIE"},
    {"code": "TV", "name": "TUVALU"},
    {"code": "UA", "name": "UKRAINE"},
    {"code": "UY", "name": "URUGUAY"},
    {"code": "VU", "name": "VANUATU"},
    {"code": "VA", "name": "VATICAN"},
    {"code": "VE", "name": "VENEZUELA"},
    {"code": "VN", "name": "VIETNAM"},
    {"code": "YE", "name": "YEMEN"},
    {"code": "ZM", "name": "ZAMBIE"},
    {"code": "ZW", "name": "ZIMBABWE"}
]

# Liste simple des noms pour les combos
COUNTRIES = [c["name"] for c in COUNTRIES_WITH_CODES]